#!/bin/bash

# A simple Git Bash script to update the version.js file with a timestamp,
# then add, commit, and push the changes.
# This script should be run in your project's root directory.

# --- 1. Generate and update version.js ---

# Get the current date and time in YYYY-MM-DD HH:MM:SS format
current_timestamp=$(date +'%Y-%m-%d %H:%M:%S')

# Define the content for version.js
# The 'export const' syntax is for JavaScript modules (ES Modules)
version_content="// This file is auto-generated by the update-version.sh script.
// It is run locally before commits to update the version number based on the current timestamp.
export const VERSION = \"${current_timestamp}\";
"

# Define the path to the js/version.js file relative to the script's location
output_file="js/version.js"

# Write the content to the version.js file
echo "${version_content}" > "${output_file}"

echo "Version updated to ${current_timestamp} in ${output_file}"

# --- 2. Git Operations ---

# Add the updated version.js file to the staging area
git add "${output_file}"
echo "${output_file} added to staging."

# Commit the changes.
commit_message="chore: Update app version to ${current_timestamp}"
git commit -m "${commit_message}"
echo "Changes committed with message: '${commit_message}'"

# Push the changes to the remote repository directly.
git push
echo "Changes pushed to remote repository."

echo "Script finished."
