#!/bin/bash

# A simple Git Bash script to update the version.js file with a timestamp.
# This script should be run in your project's root directory before committing.

# Get the current date and time in YYYYMMDDHHMMSS format
# %Y: Year (e.g., 2023)
# %m: Month (01-12)
# %d: Day (01-31)
# %H: Hour (00-23)
# %M: Minute (00-59)
# %S: Second (00-60)
current_timestamp=$(date +%Y%m%d%H%M%S)

# Define the content for version.js
# The 'export const' syntax is for JavaScript modules (ES Modules)
version_content="// This file is auto-generated by the update-version.sh script.
// It is run locally before commits to update the version number based on the current timestamp.
export const VERSION = \"${current_timestamp}\";
"

# Define the path to the js/version.js file relative to the script's location
output_file="js/version.js"

# Write the content to the version.js file
echo "${version_content}" > "${output_file}"

echo "Version updated to ${current_timestamp} in ${output_file}"
